// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Decrypt(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function Encrypt(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetOs():Promise<string>;

export function GetPDFInfo(arg1:string):Promise<main.PDFInfo>;

export function OpenDir():Promise<string>;

export function OpenFiles():Promise<Array<string>>;
