// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fs} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Metadata(arg1:string):Promise<fs.FileInfo>;

export function OpenFiles():Promise<Array<string>>;
