// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Encrypt(arg1, arg2, arg3) {
  return window['go']['main']['App']['Encrypt'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Metadata(arg1) {
  return window['go']['main']['App']['Metadata'](arg1);
}

export function OpenFiles() {
  return window['go']['main']['App']['OpenFiles']();
}
